language: python

virtualenv:
  system_site_packages: true

python:
  - "2.6"
  - "2.7"
  - "pypy"

before_script:
  - sudo apt-get install python-rpm
  - pip install -r requirements.txt

script:
  - python setup.py test
  - python setup.py sdist
